### ISSUE TITLE
Improve defineAsCustomElements (CustomElementsMode) docs.

### ISSUE THREAD

**Issue by yandeu** [nanojsx/nano#71]

**Comment by yandeu** [comment]
## Todos

- [ ] Show how to import it.
- [ ] Describe usage in SSR/Isomorphic (which will be available soon).
- [ ] Write about [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) and [Window.customElements](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements).

**Comment by jrson83** [comment]
Feel free to use/extend this code for the docs, if you like:

```JSX
import * as Nano from 'nano-jsx'
import { Component } from 'nano-jsx/lib/component'
// import defineAsCustomElements
import { defineAsCustomElements } from 'nano-jsx/lib/customElementsMode'

// create a class for a custom element
// you can also create as a functional component
class CustomElementCounter extends Component {
  value = 0

  // some custom css from Nano JSX
  static style = `
.code-result {
  border-radius: 4px;
  padding: 24px;
  margin-top: 8px;
  max-width: 100%;
  box-shadow: 4px 4px 20px 6px rgb(123 123 159 / 20%);
}
.code-result div {
  font-size: 22px;
}
.code-result button {
  cursor: pointer;
  border: none;
  background: #ff4e6a;
  color: white;
  padding: 12px 16px;
  border-radius: 4px;
  font-size: 18px;
  margin-top: 16px;
  outline: none;
}

.code-result button:first-of-type {
  margin-right: 10px;
}
`

  changeValue(newValue: number) {
    this.value += newValue
    this.update()
  }

  render() {
    return (
      <div class="code-result">
        <div id="counter-value">Counter: {this.value}</div>
        <button id="button-increment" onClick={() => this.changeValue(1)}>Increment</button>
        <button id="button-decrement" onClick={() => this.changeValue(-1)}>Decrement</button>
        <style>
          {CustomElementCounter.style}
        </style>
      </div>
    )
  }
}

// define your custom element
defineAsCustomElements(
  // your Nano Component name
  CustomElementCounter,
  // your custom elements name
  // this is equivalent to CustomElementCounter.define's first argument
  'custom-element-counter',
  // optional component's props key or multiple keys
  // use [] when not assigning keys
  ['value'],
  // optional attach a shadow root to a custom element with mode: open / closed
  // more info here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
  { mode: 'open' }
)

// create your App and include your custom component
// optional split up your custom element into a single file
// and include it in a component or page with:
// <script src="webcomponents/custom-element-counter.js"></script>
const App = () => (
  <div id="content">
    <h1>Hello from Nano JSX!</h1>
    <custom-element-counter></custom-element-counter>
  </div>
)

// render the App
Nano.render(<App />, document.getElementById('root'))
```
